spring.application.name=usuarios
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/usuarios}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=${FLYWAY_ENABLED:true}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.rabbit.enabled=false
springdoc.swagger-ui.config-url=/usuarios/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/usuarios/v3/api-docs
springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8000/usuarios/swagger-ui/oauth2-redirect.html
springdoc.swagger-ui.disable-swagger-default-url=true
app.jwt.private-key=${JWT_PRIVATE_KEY:file:/run/secrets/jwt-private.pem}
app.jwt.public-key=${JWT_PUBLIC_KEY:file:/run/secrets/jwt-public.pem}
app.jwt.issuer=${JWT_ISSUER:gateway-distribuidas}
app.jwt.audience=${JWT_AUDIENCE:parking-api}
app.jwt.access-minutes=${JWT_ACCESS_MINUTES:15}
app.jwt.refresh-days=${JWT_REFRESH_DAYS:7}
app.internal.service-token=${INTERNAL_SERVICE_TOKEN:change-me-internal-token}
app.bootstrap.enabled=${BOOTSTRAP_ENABLED:true}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
app.rabbitmq.audit.exchange=${RABBITMQ_EXCHANGE:audit_exchange}
app.rabbitmq.audit.routing-key=${RABBITMQ_ROUTING_KEY:audit_event}
server.forward-headers-strategy=framework
